### ISSUE TITLE
 what does Main quality profile  mean?

### ISSUE THREAD

**Issue by nasssssss2363** [Feramance/qBitrr#102]
Main quality profile
MainQualityProfile = "CHANGE_ME"

Temp quality profile
TempQualityProfile = "CHANGE_ME"

What's the difference with [Sonarr-TV]? Can I put Chinese in MainQualityProfile?

**Comment by Feramance** [comment]
for these configs to work, the config `UseTempForMissing` needs to be enabled. What these configs do is you can setthe `MainQualityProfile` to the quality profile your instance defaults to, set up a temporary quality profile with lower CF scores or broader quality options, and qBitrr will change the quality profile to the temp one when the movie is missing, and set it back to the main profile once found.

**Comment by nasssssss2363** [comment]
> for these configs to work, the config `UseTempForMissing` needs to be enabled. What these configs do is you can setthe `MainQualityProfile` to the quality profile your instance defaults to, set up a temporary quality profile with lower CF scores or broader quality options, and qBitrr will change the quality profile to the temp one when the movie is missing, and set it back to the main profile once found.

thank u

**Comment by drmetro09** [comment]
Can we set more than 1 quality profiles in main and temp ? separated by commas ….. as i have multiple quality profiles based on language ..etc etc

**Comment by Feramance** [comment]
If you'd like I can work on changes to support multiple, but currently it only supports one default and one temp

**Comment by Feramance** [comment]
My personal recommendation will always be to have two Radarr instances as everything just works better that way, but I'll look into this

**Comment by drmetro09** [comment]
> My personal recommendation will always be to have two Radarr instances as everything just works better that way, but I'll look into this

True , but for me now this multiple temp quality profiles will be very helpful

**Comment by drmetro09** [comment]
> If you'd like I can work on changes to support multiple, but currently it only supports one default and one temp

Hi , just out of curiosity is this implemented in 4.9.18 ?

**Comment by Feramance** [comment]
No, when it's implemented this ticket will be closed, so as long as this is open, it is not implemented

**Comment by drmetro09** [comment]
New problem cropped up, even though there is eligible release in main quality profile sonarr is not grabbing it and than qbitrr is shifting to temp quality profile in which there is no grab … so it is possible for qbitrr to shift back to main quality profile if there is no grab in temp quality profile ? 
                                                                                 OR ( just an idea) 

we can set a counter for example  3 times search in main quality profile if 3rd time didnt find eligible release than only shift to temp quality profile if still no eligible release in temp quality profile shift back to main profile and loop it . 

I desperately need this as i have to manually do the shifting of the quality profiles.

**Comment by Feramance** [comment]
I suggest you disable this functionality for the time being.

The aim of that setting is to duplicate your main profile, adjust the minimum custom format to be negative and use that as the temp profile, so you'll have the same rules just allowing for 'non ideal' copies to be grabbed.

And this only works to set all missing to temp, and all not missing to main (if the profile is the missing one)

**Comment by drmetro09** [comment]
No , in the main profile we can set one profile and temp we can set another, there is no duplicate main profile in the temp , the profile in the temp is different profile which i have set manually in the config.toml

**Comment by Feramance** [comment]
What I mean is duplicate the profile in radarr

**Comment by drmetro09** [comment]
No in config file in both sonarr and radarr we can set two different profiles there is no duplicating main profile whats it doing is its switching from main to temp profile both have different profiles set

![IMG_1478](https://github.com/user-attachments/assets/137879bb-e572-45a2-8cb2-ff4ad40366b0)

**Comment by drmetro09** [comment]
> New problem cropped up, even though there is eligible release in main quality profile sonarr is not grabbing it and than qbitrr is shifting to temp quality profile in which there is no grab … so it is possible for qbitrr to shift back to main quality profile if there is no grab in temp quality profile ? OR ( just an idea)
> 
>THIS IS THE IDEA :  we can set a counter for example 3 times search in main quality profile if 3rd time didnt find eligible release than only shift to temp quality profile if still no eligible release in temp quality profile shift back to main profile and loop it .
> 
> I desperately need this as i have to manually do the shifting of the quality profiles.

Please can you consider this idea in the future update

**Comment by Feramance** [comment]
I don't think you've understood the idea behind it, my fault for not clarifying. Here goes:

First off, there is no way to easily keep count of number of searches done to switch back, and this also defeats the purpose as a whole. 

The reasoning behind this feature is as follows, say you're using TrashGuides quality profile with minimum cf score 500 and a bunch of -10000 cf which blocks a number of releases from being grabbed, or maybe quality could be a problem for grabbing.

To resolve this, you can duplicate the quality profile in Radarr/Sonarr, set a minimum cf score to -50000 for example, or add lower quality options, and use this new quality profile as the temp profile, and the main one as the main. This way so long as the movie/series is missing, then Radarr/Sonarr will grab anything the highest cf score torrent they find which fits the quality profile (in this case potentially with a negative cf score) but at least it helps to find something.

Once something is found and imported, then the profile is switched back to the main one so that future torrents are grabbed based on the main profile post finding a file.

Its a temp profile until a file is found, not for x amount of searches, doesn't make sense otherwise as if you didn't find with the temp, there's likely no chance at all you'll find without it (if you follow the above idea)

If you follow this idea then both profiles would be essentially in line with your desired content with a slight adjustment to allow something of lower quality if nothing else can be found, but still allowing for future upgrades based on your main profile

**Comment by drmetro09** [comment]
But currently this feature is disabled right in the recent update , because it doesn’t switch to temp profile now

**Comment by Feramance** [comment]
Can you send me `TRACE` logs and your config so I can take a look please?

**Comment by drmetro09** [comment]
[config.txt](https://github.com/user-attachments/files/17791631/config.txt)

this is my config file , i cannot attach the trace logs here hope u understand, but i assure trace logs don’t mention anything about profile switching like they used to mention before

**Comment by Feramance** [comment]
So all good now?

**Comment by drmetro09** [comment]
Yes but im still chronically about the feature to add multiple temp profiles under temp

**Comment by Feramance** [comment]
I'll work on it dw

**Comment by drmetro09** [comment]
Hi , has this been implemented in the recent release? 😃

**Comment by Feramance** [comment]
No, it's still in the works

**Comment by drmetro09** [comment]
Sorry for asking, but im very excited to try the multiple temp profiles @Feramance

**Comment by Feramance** [comment]
Hi @drmetro09, I should have it ready soon

**Comment by drmetro09** [comment]
> Hi @drmetro09, I should have it ready soon

Thanks, waiting for it soon as i have another problem with qbitrr it's that it's searching and grabbing movies which are marked as unmonitor as well .

**Comment by Feramance** [comment]
Go ahead and open a ticket for it

**Comment by Feramance** [comment]
@drmetro09 feature complete, update your config accordingly and update

**Comment by drmetro09** [comment]
So now we can add multiple quality profiles separated by , example [ “WebDL1080p”, “HD720p”] this format ?

**Comment by Feramance** [comment]
Yes that's right

**Comment by drmetro09** [comment]
To pair quality profiles, ensure they are in the same order as in the temp profiles what does this mean ?

**Comment by Feramance** [comment]
For example as shown below, the main profile has the same index in the list as the index in the temp list
```toml

# Main quality profile
MainQualityProfile = ["SQP-1 (1080p)", "Anime"]

# Temp quality profile
TempQualityProfile = ["SQP-1 (1080p) - Temp", "ANime - Temp"]
```

**Comment by drmetro09** [comment]
But i want to put only 1 profile as main and than 4 profiles as temp which should cycle among themselves until the episode/movie is grabbed

**Comment by Feramance** [comment]
How would that even work?

**Comment by drmetro09** [comment]
My main profile : local language + english , if i dont get any release in local language + English ( dual audio ) , it should shift to temp profile : 1st temp profile : local language +english ( but English is given more score so even if local language is not there and English is there itll grab the release ) , 2nd temp : English only , 3rd temp profile:  no language restriction ( anything will be ok ) … and then the temp profile switches from 1st to 2nd to 3rd until it grabs something, 2nd loop does the same , 3rd loop … looping until i get atleast something…. When it finally grabs .. shift from temp to main profile.

this is what i want.. it may sound weird but its what i want 😅

**Comment by Feramance** [comment]
You could try the following:
```toml
# Main quality profile
MainQualityProfile = ["Main", "Temp1", "Temp2"]

# Temp quality profile
TempQualityProfile = ["Temp1", "Temp2", "Temp3"]
```

**Comment by drmetro09** [comment]
I am asking for switching of temp profiles because suppose a movie is available in local language but one first search radarr didn’t grab it and got shifted to temp 2 profile which is english only,  now even if the movie becomes available in local language later on radarr wont be able to grab it because the temp profile now locked to temp 2 English only as the movie is never going to be available in English

**Comment by drmetro09** [comment]
> What Radarr/Sonarr version are you using please?

V4.0

**Comment by Feramance** [comment]
> You could try the following:
> 
> ```toml
> # Main quality profile
> MainQualityProfile = ["Main", "Temp1", "Temp2"]
> 
> # Temp quality profile
> TempQualityProfile = ["Temp1", "Temp2", "Temp3"]
> ```

Try this and let me know how it goes

**Comment by drmetro09** [comment]
Ok

**Comment by drmetro09** [comment]
Can you explain how the switch happens so i can put those profiles accordingly

**Comment by drmetro09** [comment]
Which one from the image below option 1 , 2 or 3?
![IMG_1584](https://github.com/user-attachments/assets/3931af0a-1d4f-4551-a834-76f34f7420de)

**Comment by Feramance** [comment]
1

**Comment by Feramance** [comment]
```toml
# Main quality profile
MainQualityProfile = ["Main", "Temp1", "Temp2"]

# Temp quality profile
TempQualityProfile = ["Temp1", "Temp2", "Temp3"]
```
As above, it will go Main > Temp1 > Temp2 > Temp3, until found. Once found it'll go Temp3 > Temp2 > Temp1 > Main

**Comment by drmetro09** [comment]
> ```toml
> # Main quality profile
> MainQualityProfile = ["Main", "Temp1", "Temp2"]
> 
> # Temp quality profile
> TempQualityProfile = ["Temp1", "Temp2", "Temp3"]
> ```
> 
> As above, it will go Main > Temp1 > Temp2 > Temp3, until found. Once found it'll go Temp3 > Temp2 > Temp1 > Main

So its option 3 from the picture i sent above ?

**Comment by Feramance** [comment]
No, let me make it even simpler:

```
main = M1, T1, T2
temp = T1, T2, T3

sequence until found M1>T1>T2>T3
sequence when found T3>T2>T1>M1
```

**Comment by drmetro09** [comment]
> ```toml
> # Main quality profile
> MainQualityProfile = ["Main", "Temp1", "Temp2"]
> 
> # Temp quality profile
> TempQualityProfile = ["Temp1", "Temp2", "Temp3"]
> ```
> 
> As above, it will go Main > Temp1 > Temp2 > Temp3, until found. Once found it'll go Temp3 > Temp2 > Temp1 > Main

This example is confusing the loop can’t be figured out , as its same in all directions please tell me from the picture i sent above so i can arrange my profiles in the order of the loop

**Comment by drmetro09** [comment]
> No, let me make it even simpler:
> 
> ```
> main = M1, T1, T2
> temp = T1, T2, T3
> 
> sequence until found M1>T1>T2>T3
> sequence when found T3>T2>T1>M1
> ```

Its same in all directions if you check it out , the loop your trying to convey me i can’t figure out which direction it is as all directions it is same

**Comment by Feramance** [comment]
There is no way I can describe it simpler than that, just replace the profiles in the toml section below with your quality profile names:

Replace Main with your main quality profile, Temp1 with your first temporary profile, Temp2 with your second and Temp3 with your third. 

```toml
# Main quality profile
MainQualityProfile = ["Main", "Temp1", "Temp2"]

# Temp quality profile
TempQualityProfile = ["Temp1", "Temp2", "Temp3"]
```

Change every instance of Temp(1-3) so if your first temporary profile is called `Temporary profile 1` then it should look as follows:

```toml
# Main quality profile
MainQualityProfile = ["Main", "Temporary profile 1", "Temp2"]

# Temp quality profile
TempQualityProfile = ["Temporary profile 1", "Temp2", "Temp3"]
```

**Comment by drmetro09** [comment]
All should have same names ? Or all different names will work ?

**Comment by Feramance** [comment]
Follow the example provided, whatever names you use is irrelevant as long as you follow the syntax

**Comment by drmetro09** [comment]
Yes , got it now , ill try it and sorry for the trouble man but I think qbitrr will be the best automation tool arr apps + qbit , just a request why dont you give it a cool looking .png icon ? You helped a alot I appreciate it .

**Comment by Feramance** [comment]
I'll eventually get to it, got the current icon from another user, though I'll update to an original one at some point, and I agree, which is why I took over the project when I saw it was abandoned, thank you

**Comment by drmetro09** [comment]
Can i get a raw.git….link of the icon which you have now ?

**Comment by Feramance** [comment]
It's available on the repo: https://github.com/Feramance/qBitrr/blob/master/logo.png

**Comment by drmetro09** [comment]
But cannot be used as icon because it doesn’t show as container icon
