### ISSUE TITLE
[ISSUE] qBitrr creating folder named from qBittorrent category.

### ISSUE THREAD

**Issue by devanteweary** [Feramance/qBitrr#104]
OK been sitting on this one a couple of months.
Didn't wanna add to your plate.

Whenever I start qBitrr, it creates the two folders in my completed torrent download folder. 
Those two folders are the two **categories** I have set up in qBitrr.
Nothing is ever put in these folders, though. 

The two folders in relation to the qBitrr container are:
* /downloads/Videos - Movies/
* /downloads/Videos - Series/

Here are my qBittorrent categories with the save path shown:

![image](https://github.com/user-attachments/assets/82d200b9-1aaa-4a38-9dcf-66bac464648f)

Here're the two folders it creates

![image](https://github.com/user-attachments/assets/92140f58-fe86-469b-8491-11140ca6e6ef)

And finally, here are the logs on startup and my config:

[qBitrr Logs](https://devante.rocks/share/qbitrr_logs.zip)

**Comment by Feramance** [comment]
I'll be adding some new configs to specify directory when category has a set directory, unless I manage to read this from the api

**Comment by devanteweary** [comment]
> Give the image `feramance/qbitrr:pr-105` a try and let me know how it goes

OK a quick update changes the behavior a little.

The old unwanted behavior - note these are the qbitorrent category titles, not paths:
* It created `/downloads/Videos - Movies/`
* It created `/downloads/Videos - Series/`

The new unwanted behavior:
* It creates `/downloads/Complete/`
* and it creates the whole paths too
* `/downloads/Complete/Media/Videos/Movies/`
* `/downloads/Complete/Media/Videos/Series/`

which translates to this in terms of the full host path:
*  `/mnt/user/Downloads/Torrents/Complete/Complete/Media/Videos/Movies/`
*  `/mnt/user/Downloads/Torrents/Complete/Complete/Media/Videos/Series/`




---

The full host path:
*  `/mnt/user/Downloads/Torrents/Complete/Media/Videos/Movies/`
*  `/mnt/user/Downloads/Torrents/Complete/Media/Videos/Series/`

My container mount setting is:
* /downloads = /mnt/user/Downloads/Torrents/Complete/

**Comment by Feramance** [comment]
Can you send me logs please? I just need the first line

**Comment by devanteweary** [comment]
> Can you send me logs please? I just need the first line

Here are the logs.
Wasn't sure which first line you wanted, here's the Radarr one: 
* Category exists with save path [/downloads/Complete/Media/Videos/Movies]
And here are the full logs: [qbitrr Logs](http://devante.rocks/share/qbitrr_logs.zip)

**Comment by Feramance** [comment]
Can you send me your docker volume mappings? As I think the issue is there

**Comment by Feramance** [comment]
Also, is your qbitrr config set to `/downloads` or `/downloads/Complete`?

**Comment by Feramance** [comment]
There's your problem, the path in qBitrr needs to be the same as in qbittorrent, try that and it should be good

**Comment by devanteweary** [comment]
OK gonna close this one. I changed the path and will monitor.  
Thanks. :>

**Comment by Feramance** [comment]
Leaving the issue open until you validate this fixed the issue for you, on my end it seems to be working

**Comment by devanteweary** [comment]
> Leaving the issue open until you validate this fixed the issue for you, on my end it seems to be working

Yeah man looks good. Several torrents downloaded and no problems at all. 
Guess that one was on me. :P' Sorry about that.

**Comment by Feramance** [comment]
No worries
