### ISSUE TITLE
What is the criteria for a torrent to be considered "slow"?

### ISSUE THREAD

**Issue by LazerDickMcCheese** [Feramance/qBitrr#107]
I don't know if I should enable or disable this because I haven't seed any metrics that qbitrr seeks. For example, what if "DoNotRemoveSlow = true" starts removing torrents within my tolerable range?

**Comment by Feramance** [comment]
The `DoNotRemoveSlow ` config is user configurable with the `MaximumETA` config

**Comment by LazerDickMcCheese** [comment]
Understood, thank you for your help
