### ISSUE TITLE
Unable to start qBitrr - Log Files

### ISSUE THREAD

**Issue by LegioN7** [Feramance/qBitrr#108]
Hey Feramance, 
I hope I can help with some issues I've been having. qBitrr will not launch if existing log files exist.
If I delete the log files, qBitrr starts.

How do you want me to send you the log?
It auto closes when this issue happens. (Is there a way to add a pause statement to crashes related to the logging?)

**Comment by Feramance** [comment]
The way to get logs for this is opening a terminal window (powershell or command prompt) and executing qBitrr in it, it'll then print out the relevant logs. This issue is most likely due to permissions

**Comment by LegioN7** [comment]
Let me see what I can do, let me see if any logfile captures this.

**Comment by Feramance** [comment]
It won't be a file, the terminal window will display the logs, then you either copy or screenshot them

**Comment by Feramance** [comment]
Any updates?

**Comment by LegioN7** [comment]
I have an update! when qBitrr closes improperly, it has a chance to make the log file "corrupt".
This is actually what's causing it to fail on startup. 

You can recreate it by crashing qBitrr with an alt+f4 during some of the steps (I'm trying to pinpoint exactly where) but when you try to re-open qBitrr it fails because the logs are invalid/incomplete and there is no pause.

**Comment by Feramance** [comment]
Good to know, I'll test this a bit and look for a solution

**Comment by Feramance** [comment]
Download the latest version (v4.9.7)and let me know how that goes

**Comment by Feramance** [comment]
Just added an update, v4.9.10, it fixes the issue for good, tested already, reopen the ticket if you have any further issues

**Comment by LegioN7** [comment]
Hey Feramance
Crashing still with the latest version
Here is all that it logs (and it still just crashes straight out without a pause)

The logs don't really capture anything and qBitrr doesn't load when the logs fail.
It's pretty bare log-wise.

I can send my config over in a bit and some other various stuff. I think at least we know it isn't a permission issue with windows (similar to my other bug) with the log files.

**Comment by Feramance** [comment]
Hi @LegioN7
I don't see any log files attached and a copy of your config would also help, alongside logs

**Comment by Feramance** [comment]
Using the latest version, run it in a terminal and see if you notice any errors, and send screenshots if possible

**Comment by Feramance** [comment]
Closing this ticket as no more info was provided and the issue should be fixed
