### ISSUE TITLE
New unraid docker install, getting AttributeError: 'PlaceHolderArr' object has no attribute 'search_setup_completed'

### ISSUE THREAD

**Issue by VicePrez** [Feramance/qBitrr#110]
The logs show the following when starting the container on a fresh docker container:

### SYSTEM / OTHER INFO

- Installed on Unraid through CA store
- Used default config.toml generated after first install
- Set root folder permissions to 1000:1000
- All other functionality seems to be working with the exception of `CustomFormatUnmetSearch = true`. It throws another series of errors. I can reproduce later in another issue.

### LOGS
`STARTING QBITRR`
`[2024-09-22 08:20:17] [pid:       1][tid:23339959544704] INFO    : qBitrr            : Starting qBitrr: Version: 4.9.3-91ade0e.`
`[2024-09-22 08:20:18] [pid:       1][tid:23339959544704] INFO    : qBitrr.Manager    : Current qBitTorrent version is supported: 4.6.7`
`[2024-09-22 08:20:24] [pid:       1][tid:23339959544704] HNOTICE : qBitrr.Sonarr-TV  : Starting Sonarr-TV monitor`
`[2024-09-22 08:20:33] [pid:       1][tid:23339959544704] HNOTICE : qBitrr.Radarr-1080: Starting Radarr-1080 monitor`
`[2024-09-22 08:20:33] [pid:       1][tid:23339959544704] HNOTICE : qBitrr.Failed     : Starting Failed monitor`
`[2024-09-22 08:20:33] [pid:       1][tid:23339959544704] HNOTICE : qBitrr.Recheck    : Starting Recheck monitor`
`Process Process-5:`
`Traceback (most recent call last):`
`  File "/usr/local/lib/python3.10/site-packages/multiprocess/process.py", line 314, in _bootstrap`
`    self.run()`
`  File "/usr/local/lib/python3.10/site-packages/multiprocess/process.py", line 108, in run`
`    self._target(*self._args, **self._kwargs)`
`  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 5025, in run_torrent_loop`
`    self.register_search_mode()`
`  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 4695, in register_search_mode`
`    if self.search_setup_completed:`
`AttributeError: 'PlaceHolderArr' object has no attribute 'search_setup_completed'`
`Process Process-6:`
`Traceback (most recent call last):`
`  File "/usr/local/lib/python3.10/site-packages/multiprocess/process.py", line 314, in _bootstrap`
`    self.run()`
`  File "/usr/local/lib/python3.10/site-packages/multiprocess/process.py", line 108, in run`
`    self._target(*self._args, **self._kwargs)`
`  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 5025, in run_torrent_loop`
`    self.register_search_mode()`
`  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 4695, in register_search_mode`
`    if self.search_setup_completed:`
`AttributeError: 'PlaceHolderArr' object has no attribute 'search_setup_completed'`
`[2024-09-22 08:20:36] [pid:       8][tid:23339959544704] HNOTICE : qBitrr.Sonarr-TV  : Starting torrent monitoring for Sonarr-TV`
`[2024-09-22 08:20:36] [pid:      10][tid:23339959544704] HNOTICE : qBitrr.Radarr-1080: Starting torrent monitoring for Radarr-1080`

### ATTACHMENTS
Config file here (had to rename extension to upload to GitHub).
[config.txt](https://github.com/user-attachments/files/17090373/config.txt)

**Comment by Feramance** [comment]
Thanks for the detailed ticket, I'll look into this when I get back from holiday

**Comment by prinzpiuz** [comment]
same here
```
STARTING QBITRR

[2024-09-27 15:58:11] [pid:       1][tid:139886059813760] INFO    : qBitrr            : Starting qBitrr: Version: 4.9.3-91ade0e.

[2024-09-27 15:58:11] [pid:       1][tid:139886059813760] INFO    : qBitrr.Manager    : Current qBitTorrent version is supported: 4.6.7

[2024-09-27 15:58:12] [pid:       1][tid:139886059813760] CRITICAL: qBitrr.ArrManager : 'sonarr-tv'

[2024-09-27 15:58:12] [pid:       1][tid:139886059813760] CRITICAL: qBitrr.ArrManager : 'radarr-1080'

[2024-09-27 15:58:12] [pid:       1][tid:139886059813760] HNOTICE : qBitrr.Recheck    : Starting Recheck monitor

[2024-09-27 15:58:12] [pid:       1][tid:139886059813760] HNOTICE : qBitrr.Failed     : Starting Failed monitor

Process Process-1:

Process Process-2:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/multiprocess/process.py", line 314, in _bootstrap

    self.run()

  File "/usr/local/lib/python3.10/site-packages/multiprocess/process.py", line 108, in run

    self._target(*self._args, **self._kwargs)

  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 5025, in run_torrent_loop

    self.register_search_mode()

  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 4695, in register_search_mode

    if self.search_setup_completed:

AttributeError: 'PlaceHolderArr' object has no attribute 'search_setup_completed'
```

**Comment by Feramance** [comment]
Updating to v4.9.5 should fix this issue

**Comment by prinzpiuz** [comment]
Working fine 
thank you @Feramance

**Comment by VicePrez** [comment]
Working fine as well, thanks @Feramance.
