### ISSUE TITLE
Problem with complete downloads folder 

### ISSUE THREAD

**Issue by drmetro09** [Feramance/qBitrr#126]
Hi , first of all its a really nice project
Secondly I would like to tell you an issue which im facing, which is even after giving correct path to the download complete folder where qbit puts the completed files the logs of qbitrr shows the folder is missing in config.toml also i have put the extact path on the host where qbit puts the completed downloads still the problem persists

**Comment by Feramance** [comment]
Hi, can you provide more info regarding  your setup, config values and logs?

**Comment by drmetro09** [comment]
Im on unraid , docker setup , i feel its something to do with the category tags .. seems like messed up please guide

![Uploading IMG_1464.jpeg…]()

**Comment by Feramance** [comment]
The image attached is not working and can you also send the qbittorrent category paths?

**Comment by drmetro09** [comment]
Update : after long 4 hours i managed to fix this by setting appropriate path in qbit for each tag and than creating same container paths in sonarr and radarr and in the config.toml i used the conatiner path of qbitrr container basically everything had to be interconnected properly than only the error went

**Comment by drmetro09** [comment]
The started updating database thing is continuously running i think every second , how to put a time limit for it ? 
Image for reference 
![IMG_1465](https://github.com/user-attachments/assets/4b9b96fc-3600-48de-b18d-07502428cbac)

**Comment by Feramance** [comment]
Can you send over your config please?

**Comment by Feramance** [comment]
> Update : after long 4 hours i managed to fix this by setting appropriate path in qbit for each tag and than creating same container paths in sonarr and radarr and in the config.toml i used the conatiner path of qbitrr container basically everything had to be interconnected properly than only the error went 

For qBitrr only qbittorrent paths mattered, but qbittorrent paths matter to Sonarr and radarr

**Comment by drmetro09** [comment]
> Sonarr and radarr

Yes correct , i had to re do everything as previously i had not setup separate separate folders for sonarr and radarr in qbit completed folder , because of the category tags had to create two separate folders in the qbit completed folder

**Comment by drmetro09** [comment]
This starting update database is running continuously even after setting time to 600 secs

**Comment by Feramance** [comment]
Can you send over your config please?

**Comment by drmetro09** [comment]
Here it is mad t a txt file so I could attach it here but im using it as config.toml file

[config.toml.txt](https://github.com/user-attachments/files/17720623/config.toml.txt)

**Comment by Feramance** [comment]
Per your config you have enabled `SearchByYear` This causes the database to be updated for every year you have content for one at a time, therefore the logging you saw is expected. I have however just pushed an update to improve the logging for that message, now including the year its checking when that config is enabled.

**Comment by drmetro09** [comment]
So should i disable it ? Its also doing RSS sync like every 10 mins i dont want that and its also not grabbing anything is there any tutorial as how to understand the config and set it accordingly

**Comment by Feramance** [comment]
There's an RSS config for the RSS sync, the config explains how to disable if desired, and it's entirely your choice whether to disable search by year or not. With it enabled the api calls are smaller and more gradual, disabled it bulk updates everything

**Comment by drmetro09** [comment]
How to enable this in config.toml
Monitor qBit for completed entries and tell the appropriate Arr instance to import it:
qbitrr DownloadedMoviesScan for Radarr
qbitrr DownloadedEpisodesScan for Sonarr ?

**Comment by Feramance** [comment]
These are enabled by default, they always work
