### ISSUE TITLE
File getting removed from arr apps que but not from qbit que

### ISSUE THREAD

**Issue by drmetro09** [Feramance/qBitrr#130]
File getting removed from arr apps que but not from qbit que 
need some help as how to enable it within the config file 

image of log showing it is attached 

![IMG_1473](https://github.com/user-attachments/assets/9b49f81d-17ae-4689-9c59-c997347d2668)

**Comment by Feramance** [comment]
The way to resolve this is with the following:
![image](https://github.com/user-attachments/assets/56ac1f1e-4921-4aab-bd79-bc5e8ea7fe6b)
For the behaviour you are experiencing to happen, you must have `StalledDelay` at a value not -1 and `ReSearchStalled` true. The way around this is to disabled `StalledDelay` by setting the value to -1

**Comment by drmetro09** [comment]
Ok ill try it

**Comment by drmetro09** [comment]
Stalldelay was -1 but researchstalled was true , im curious to know what researchstalled does ?

**Comment by Feramance** [comment]
`ReSearchStalled` works in conjunction with `StalledDelay` (I may need to ensure that, and causes a search command to be send when a torrent is allowed to be stalled for x amount of time
