### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by drmetro09** [Feramance/qBitrr#132]
Ignore slow torrents.
DoNotRemoveSlow = true

 Re-search stalled torrents
ReSearchStalled = true

Maximum allowed time for allowed stalled torrents in minutes (-1 = Disabled, 0 = Infinite)
StalledDelay = 1440

Im breaking my head with this config setup , I want to know what these options i listed above do ? The behaviour i want is when a download is stalled for 20 mins Qbittorent should remove it , radarr or sonnar should remove it from its que  and blocklist the torrent and do a fresh search for same file right away … how do I achieve this ? Need some guidance 
Thanks

**Comment by drmetro09** [comment]
> Before I give a valid answer, do you want to allow all torrents a minimum of 20 mins, or just stalled torrents?

Just the stalled ones.

**Comment by Feramance** [comment]
Then set the following:

```toml
DoNotRemoveSlow = true
StalledDelay = 20
ReSearchStalled = false
```

This will still cause the re-search but after removing the stalled torrent, if you want to trigger a search once the torrent is detected as `Stalled`, then set `ReSearchStalled` to true

**Comment by drmetro09** [comment]
> Then set the following:
> 
> ```toml
> DoNotRemoveSlow = true
> StalledDelay = 20
> ReSearchStalled = false
> ```
> 
> This will still cause the re-search but after removing the stalled torrent, if you want to trigger a search once the torrent is detected as `Stalled`, then set `ReSearchStalled` to true

Will this also add the stalled torrent to blocklist of sonarr/ radarr ?

**Comment by Feramance** [comment]
Anytime a stalled torrent is removed, it is always blocklisted

**Comment by drmetro09** [comment]
> Anytime a stalled torrent is removed, it is always blocklisted

No its not getting blocklisted , its just removed there must be some configuration which we are missing

**Comment by drmetro09** [comment]
More info : The picked up torrent appears to be in qbittorrent but not in radarr que

**Comment by Feramance** [comment]
Give it time, qBitrr will force refresh the Radarr queue. If its still not picked up then it's not a qBitrr issue

**Comment by drmetro09** [comment]
Its removing from qbittorrent but than grabbing the same release again as the previous stalledone was blocklisted , its not blocklisting automatically thats the problem

**Comment by Feramance** [comment]
Did you check and refresh your blocklist on Radarr/Sonarr?

**Comment by drmetro09** [comment]
> Did you check and refresh your blocklist on Radarr/Sonarr?

Yes sir , its not there

**Comment by Feramance** [comment]
Can you send me trace logs logging this exact thing happening?

**Comment by drmetro09** [comment]
What does # Re-search stalled torrents
ReSearchStalled = true option do ? If i set it to false will it not research for the stalled torrent which has been removed?

**Comment by Feramance** [comment]
> Update: after research I found out that there is something wrong with qbit 5.0 api so if the file is stalled from beginning it doesn’t show on radarr queue , so if it doesn’t show qbitrr cannot remove it or blocklist it . So the problem is with qbit 5.0 api

Yes these seems to be a qbittorrent 5 issue, it's still has a number of issues with regards to it's api, I'll list that 5.0 is not supported yet
