### ISSUE TITLE
Deleting files while they are downloading 

### ISSUE THREAD

**Issue by drmetro09** [Feramance/qBitrr#134]
Yesterday witnessed a stranged issue qbitrr searched for missing episodes, than found it , put into download que , file was 20gb , than after the download reached some 8gb it just deleted it from que and started research for the same file , found exact same file but this time from other indexer and same thing happened, it kinda wasted 8 + 8gb 16gb data .

what could have been wrong ?

**Comment by Feramance** [comment]
Check logs, they'll tell you why it was removed

**Comment by drmetro09** [comment]
> Check logs, they'll tell you why it was removed

Logs are unclear it just showed deleted followed by the gran id

**Comment by Feramance** [comment]
Then set your logs to `TRACE` and take note of when this happens again, or try to reproduce and check/send the logs
