### ISSUE TITLE
Grabbing unmonitored episodes/movies

### ISSUE THREAD

**Issue by drmetro09** [Feramance/qBitrr#139]
I add a movie monitored and i uncheck the box in radarr where it says search for the movie after adding it , than when qbitrr runs it tells radarr that movie is monitored and missing so radarr searches for the movie grabs it and sends to qbitorrent for download…. This is normal but problem is if i change my mind and i no longer wanted that movie and i cancel the download from qbitorrent and remove it torrent+ files , and unmonitor the movie in radarr surprisingly qbitrr still forces radarr to search and grab the movie and send it to qbitorrent even if its unmonitored now !!!!

**Comment by drmetro09** [comment]
> I will look into this and fix accordingly, in the meantime, it is best practice to delete movies you don't want downloaded from Radarr, unless the movie is downloaded and you don't want it to change the file

Yes , but this issue has cropped up suddenly before if i clicked unmonitor qbitrr used to ignore it , but now qbitrr goes on grabbing the files untill it’s downloaded it wont stop !

**Comment by Feramance** [comment]
restart qbitrr

**Comment by drmetro09** [comment]
> restart qbitrr

I tried but same

**Comment by Feramance** [comment]
Adding new config, take a look at the `Unmonitored` config in the example provided in the repo once released, I'll inform you

**Comment by Feramance** [comment]
@drmetro09 feature complete, update your config accordingly and update
