### ISSUE TITLE
Duplicating downloads 

### ISSUE THREAD

**Issue by KidAmnesiac1** [Feramance/qBitrr#147]
I've just setup qbitrr with sonarr, and I'm seeing duplicate downloads of episodes. I don't see anything in the logs that would indicate why this is happening.

Any ideas?

<img width="1344" alt="Screenshot 2024-12-12 at 20 34 06" src="https://github.com/user-attachments/assets/7fbfbd26-60db-4b45-a4ca-c253ca4f7813" />

**Comment by Feramance** [comment]
Hi, can you send me trace logs so I can take a look at them?
