### ISSUE TITLE
How to increase the time qbitrr tells sonarr and radarr to search ?

### ISSUE THREAD

**Issue by drmetro09** [Feramance/qBitrr#150]
How to increase the time qbitrr tells sonarr and radarr to search for files because its doing it very frequently again and again and hammering the indexers , how do I increase the timer make it time gap between searches longer ?

**Comment by Feramance** [comment]
This config:
```
# Time to sleep between posting search commands (in seconds: 600 = 10 Minutes)
SearchLoopDelay = -1
```

**Comment by drmetro09** [comment]
-1 would make it do what ? Could you please explain i don’t want to stop the process rather just delay it

**Comment by Feramance** [comment]
As  described in the description of the config itself, `(in seconds: 600 = 10 Minutes)`. `-1` means disabled (no delay) so give it a value as described in the description. There's no limit to delay length

**Comment by drmetro09** [comment]
-1 would cause it to search again and again and spam the indexers !!!

**Comment by drmetro09** [comment]
What i want is qbitrr should trigger the search in sonarr and radarr and than itself should sleep for next 30 minutes and than again wake up after 30 mins and trigger search again .

**Comment by Feramance** [comment]
Ok, so set the value of the config to...

As shown is description, the value needs to be in seconds and 600 seconds = 10 minutes, so 30 mins = 1800 seconds. Just set that value

**Comment by Feramance** [comment]
RSS Sync and search are two completely different things. RSS Sync is the default behaviour for Sonarr and Radarr on how they find new releases, while search is an actual search specific for each item. In my case for example I outright disabled the RSS sync and told qBitrr to send search commands every 60 seconds

**Comment by drmetro09** [comment]
Is it possible that qbitrr will search all the missing, monitored items one after another and than start again after 30 mins I don’t want to delay in between search rather I want qbitrr to conduct all searches every 30mins

**Comment by drmetro09** [comment]
> RSS Sync and search are two completely different things. RSS Sync is the default behaviour for Sonarr and Radarr on how they find new releases, while search is an actual search specific for each item. In my case for example I outright disabled the RSS sync and told qBitrr to send search commands every 60 seconds

if i disable rss sync in config of qbitrr will it never cause rss sync in sonarr and radarr ? Because i know there is rss sync option in sonarr and radarr which i set to 60mins ( default)

**Comment by drmetro09** [comment]
What does # Delay between request searches in seconds
SearchRequestsEvery = 300 this do ?

**Comment by drmetro09** [comment]
> It delays the request search by the amount of seconds configured, though request search is currently disabled due to some issues until they are fixed

Is it same as # Time to sleep between posting search commands (in seconds: 600 = 10 Minutes)
SearchLoopDelay = -1 ? What’s the difference between both?

**Comment by Feramance** [comment]
One is for general searches, one is for request searches

**Comment by drmetro09** [comment]
> Is it possible that qbitrr will search all the missing, monitored items one after another and than start again after 30 mins I don’t want to delay in between search rather I want qbitrr to conduct all searches every 30mins

Is this possible?

**Comment by Feramance** [comment]
Then you need this config:
```
# Time to sleep between reprocessing torrents (in seconds: 600 = 10 Minutes)
LoopSleepTimer = 60
```

Just change the value as desired. 30 minutes = 1800

**Comment by drmetro09** [comment]
Its very confusing now , my main concern is qbitrr is causing searches in sonarr and radarr and missing epi , monitored stuff again and again too much and its hitting and spamming the indexers i just want qbitrr to do its job every 30 mins and than sleep and not sleep in between commands.

**Comment by drmetro09** [comment]
# Time to sleep between reprocessing torrents (in seconds: 600 = 10 Minutes)
LoopSleepTimer = 60 What does this do ? Does this trigger the search for missing episodes?

**Comment by Feramance** [comment]
I fixed the values and I already explained what you're asking me. The configs all have descriptions and are very clear on what they do
