### ISSUE TITLE
Crashes on start up

### ISSUE THREAD

**Issue by Wayno** [Feramance/qBitrr#30]
Came across this trying to set it up. Crashes on start up

Python error.
[log.txt](https://github.com/Feramance/qBitrr/files/13317100/log.txt)

Windows Server 2019

**Comment by Feramance** [comment]
Could you please send a screenshot of your folder structure, a copy of your config (removing any sensitive info) and can you confirm you installed all the requirements as instructed?

**Comment by Feramance** [comment]
Marking as resolved due to inactivity
