### ISSUE TITLE
Not Enough Values To Unpack Error

### ISSUE THREAD

**Issue by TurtleHead36** [Feramance/qBitrr#31]
Windows 10 running Docker Desktop using Docker Compose [Docker Compose.txt](https://github.com/Feramance/qBitrr/files/13326552/Docker.Compose.txt)
When I run the terminal returns, [Terminal Log.txt](https://github.com/Feramance/qBitrr/files/13326553/Terminal.Log.txt) any help would be much appreciated have been troubleshooting this for weeks now. My config in the event you require it [Config.txt](https://github.com/Feramance/qBitrr/files/13326551/Config.txt) 
(If you need anything else please reach out I am new to this whole scene so paths for logs, etc would be appreciated)

**Comment by Feramance** [comment]
Have you tried running it in a folder outside of AppData? say C:/qbitrr to test?

**Comment by TurtleHead36** [comment]
Okay, so I changed it to C:/qbitrr ran the container here's the [Terminal Log.txt](https://github.com/Feramance/qBitrr/files/13338655/Terminal.Log.txt)

Same error however it did pause a torrent, which it hasn't done before.

**Comment by Feramance** [comment]
Could you try running qBitrr using Admin privileges? I think you have a permissions issue somehow somewhere

**Comment by TurtleHead36** [comment]
I'm not entirely sure how you would give a Container Admin Privilege, But I tried two things that resulted in no change to the logs

First I ran DockerDesktop as Admin and ran the container
Then I added the flag --privileged to the container

To my knowledge this should have allowed access, but if Im incorrect I would appreciate any help you could provide

**Comment by Feramance** [comment]
You're right, sorry forgot you are on windows Docker, could you kindly test the latest testing image? use `feramance/qbitrr:testing`

**Comment by TurtleHead36** [comment]
I changed the image and ran this [Docker Compose.txt](https://github.com/Feramance/qBitrr/files/13355086/Docker.Compose.txt) I even made sure it had admin perms

output seems to be the exact same error
[Terminal Log.txt](https://github.com/Feramance/qBitrr/files/13355087/Terminal.Log.txt)

**Comment by Feramance** [comment]
For the sake of it, can you try running it without the `:ro` and `:rw` suffixes for the volumes?

**Comment by Feramance** [comment]
This could also be a windows docker limitation, I would suggest running the executable instead for windows if you can

**Comment by TurtleHead36** [comment]
Okay, so I fixed it! just not in the traditional way..

I uninstalled my entire OS and reinstalled it then completely rebuilt my media server. (I was already planning on doing this do this, it was my first time and was inefficient) after configuring my Arrs everything is working great HOWEVER I still receive the exact same database error, but I do not receive the unexpected value error. My best guess is this was not an issue with your tool, but rather an issue with my Sonarr and Radarr databases corrupting/errorring.

I am extremely grateful for your support and speedy replies, I absolutely love the tool and couldn't operate well without it.

**Comment by Feramance** [comment]
Good to hear that issue was resolved. Might I suggest disabling `SearchByYear` to remove the database error for the time being. The tool isn't originally mine but I couldn't help but take it up after the original dev closed it as it was a requirement for me
