### ISSUE TITLE
[Feature Request]: Ability to specify a tag to ignore even when radarr/sonarr category is present

### ISSUE THREAD

**Issue by milindpatel63** [Feramance/qBitrr#33]
We can define and assign tags to torrents on qbittorrent.

And sometimes, some torrents only get download speed at specific times of the day and the rest of the time they are stalled.

So a way to manually exclude them from getting removed via qbitrr would be to assign some tags to them and specify qbitrr to ignore torrents with specific tags.

Right now, i have to stop qbitrr sometimes when it keeps removing my stalled torrents which i know might get completed if i just waited a bit.

**Comment by Feramance** [comment]
In reality this functionality already exists in a different manner. Not sure if it suits your needs though. As is in order to have qBitrr ignore any torrents I add manually, I simply give the torrent a category I created called manual. since this category is not configured in my qBitrr config, all torrents in it are ignored

**Comment by milindpatel63** [comment]
> In reality this functionality already exists in a different manner. Not sure if it suits your needs though. As is in order to have qBitrr ignore any torrents I add manually, I simply give the torrent a category I created called manual. since this category is not configured in my qBitrr config, all torrents in it are ignored

I'm not talking about adding torrent manually.
I still want radarr/sonarr category to be there so that when torrent completes, radarr/sonarr can import it.
But i want to exclude some torrents from qbitrr which may look to be stalled but might complete after some time.

**Comment by Feramance** [comment]
Understood, I'll try have it done by end of week

**Comment by Feramance** [comment]
Apologies this is taking longer than expected but the Holidays provide a lot of distractions

**Comment by Feramance** [comment]
You can start testing this feature on the latest `nightly` build for the time being

**Comment by milindpatel63** [comment]
> You can start testing this feature on the latest `nightly` build for the time being. The new tag should be automatically created in qbittorrent for you, just use it `qbitrr-allowed_download`

So i tried it. Added a torrent for a movie via radarr which had almost 0 seeds/peers, then applied the qbitrr-allowed_download tag to it, then the torrent got stalled for a while, but qbitrr still removed it and initiated a re-search for that movie and added a different torrent.

What i had in mind was,
There should be a tag.
When we apply that tag to any torrent in qbittorrent, qbitrr should ignore those torrents and NOT remove them even IF they are stalled.

**Comment by Feramance** [comment]
Yes that is the aim of this, I'll keep looking into it and let you know when you should update. Once it's working correctly I'll push the release. Could you send me the magnet link of the torrent you're using?

**Comment by milindpatel63** [comment]
> Yes that is the aim of this, I'll keep looking into it and let you know when you should update. Once it's working correctly I'll push the release. Could you send me the magnet link of the torrent you're using?

Got it.
Here's the torrent i'm using: https://thepiratebay.org/description.php?id=68845302
Magnet:
```
magnet:?xt=urn:btih:CFEEFD4328541DE606A55FF3461B042D7B0BFEE1&dn=John%20Wick%20Chapter%204%202023%20720p%20WEB-DL%20DDP5%201%20Atmos%20H%20264-CM&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.bittor.pw%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=udp%3A%2F%2Fpublic.popcorn-tracker.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce
```

**Comment by Feramance** [comment]
For better readability I changed the tag to `qbitrr-ignored` and made some changes. Feel free to test it

**Comment by Feramance** [comment]
Please update to the latest version, functionality should be ready

**Comment by milindpatel63** [comment]
Can confirm that it works now.
I added a torrent via radarr which had 0 seeds and then tagged it with the new ```qbitrr-ignored``` tag, and then it was stuck on stalled with no intervention from qbitrr as expected. Then when i removed the tag, qbitrr removed that torrent in a while and marked it as failed in radarr as expected.

Thank you for your efforts.!! :D
