### ISSUE TITLE
Good getting started turotial available ?

### ISSUE THREAD

**Issue by wamak9** [Feramance/qBitrr#45]
Hello, I discovered qbit recently and its prety straight forward to install(I am using truenas scale).
Only issue I have is how to manage the configuration when installed on truenas scale.
How do I setup the configuration ?
I am not able to find a proper guide on how config can be setup.
I also use traefik with truenas scale.

Can I just edit the config.toml file and then restart the container to pick up the changes.
Not sure how to get these on truennas scale.
```
- /path/to/sonarr/db:/sonarr.db:ro # This is only needed if you want episode search handling :ro means it is only ever mounted as a read-only folder, the script never needs more than read access
      - /path/to/radarr/db:/radarr.db:ro # This is only needed if you want movie search handling, :ro means it is only ever mounted as a read-only folder, the script never needs more than read access
```
Any help would be appreciated.

**Comment by Feramance** [comment]
Realistically you got it, just edit the config and restart, something doesn't work, either you'll notice it or qBitrr will inform you through the logs. With regards to those path, you 'll need to provide access to the storage location where your Radarr and Sonarr configs are then place the paths to the `.db` file in the configs

**Comment by wamak9** [comment]
> Realistically you got it, just edit the config and restart, something doesn't work, either you'll notice it or qBitrr will inform you through the logs. With regards to those path, you 'll need to provide access to the storage location where your Radarr and Sonarr configs are then place the paths to the `.db` file in the configs

let me give that a try. Hopefully it will work out, thanks for the info.

**Comment by Feramance** [comment]
If you manage, please close the issue as resolved

**Comment by wamak9** [comment]
yeah, I am able to figure out the .db file location.
