### ISSUE TITLE
Ability to Specify Multipe radarr & sonarr servers

### ISSUE THREAD

**Issue by wranglatang** [Feramance/qBitrr#46]
Hello, I havent been able to use this yet but it seems like a really great tool! the one thing that is preventing me from adopting is the fact that i cant seem to specify multiple Radarr & Sonarr DB's. In my setup i have 3 Radarr's (1 for HD, 1 for 4K & 1 for Kids Movies) then i have two Sonarr (1 for HD & 1 for Kids Shows). These different arr servers are reflected in the Tags that qBit has (radarr, radarr-4k, radarr-kids, sonarr, sonarr-kids).

Happy to test things out :)

**Comment by Feramance** [comment]
There's no problem, you can have multiple DB's just give them different names unless using different paths, then in the config file you need to configure each Radarr/Sonarr config as needed with the appropriate DB names/paths and ensure that only the Radarr 4K instance is enabled as 4K

**Comment by wranglatang** [comment]
Have you got an example you can share? I’m going to be using this on unraid using the community store to install

Kind Regards

Philip Wrangles

***@***.***
07742601616

**Comment by Feramance** [comment]
> I see now that you have a very extensive example config file. I shall take a read through and see if I can get it working and then open up another issue if I have an issue! thanks! 

Happy to help if needed. I suggest not using the series search option for now as I'm encountering some issues which I am looking into
