### ISSUE TITLE
Radarr/Sonarr Log Errors + Pausing of Completed Downloads Unraid.

### ISSUE THREAD

**Issue by Healzangels** [Feramance/qBitrr#51]
Greetings! 
Thanks for creating/sharing such an awesome sounding tool! 
I like a few other issue threads I saw recently set this up on my unraid system.

Able to connect QBittorrent/Sonarr/Radarr alright but having a few small issues.

The main issue I am facing seems to be in my Radarr logs. I currently am seeing the logs filling with the following error below. 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 2117, in db_update_single_series
    movieData = self.client.get_movie_by_movie_id(db_entry["id"])
TypeError: 'builtin_function_or_method' object is not subscriptable
'builtin_function_or_method' object is not subscriptable
```
![Radarrlog](https://github.com/Feramance/qBitrr/assets/47136415/c2c01bc0-8b07-4b9a-8236-99eeb6b3bc34)

In addition I am also seeing the following error at the top of the logs in both my Sonarr + Radarr logs. 

```
Pausing Completed torrent: [Progress: 100%][Added On: 2024-01-07 20:30:29][Availability: -100%][Time Left: 100 days, 0:00:00][Last active: 2024-01-07 21:38:15] | [TorrentState.STALLED_UPLOAD] | redacted (7b2a0b82861bc5d5624eb037a9d6c0c394141d8d)
Downloaded scan error: [/data/torrents/movies/redacted][2B3F2B66E5D4D84FC836736B2CF8B0DA716575A3][Hardlink]
```

This is present for both within my Sonarr and Radarr logs. 

And lastly I believe I am seeing the same behavior mentioned https://github.com/Feramance/qBitrr/issues/47#issuecomment-1881248496 
I have confirmed my config has seeding settings (pretty much all settings at this point) set to `-1` however I am seeing all my seeding stopped and marked as done. Guessing this might have something to do with the error above and the 

```
Pausing Completed torrent: [Progress: 100%][Added On: 2024-01-07 20:30:29][Availability: -100%][Time Left: 100 days, 0:00:00][Last active: 2024-01-07 21:38:15] | [TorrentState.STALLED_UPLOAD] | redacted (7b2a0b82861bc5d5624eb037a9d6c0c394141d8d)
```

Thanks again for sharing such a coo sounding tool and can't wait to really get to use it.

If I can provide any additional screenshots/config logs etc let me know and happy to post.
-Cheers!

**Comment by Healzangels** [comment]
Additional information: 
QBitrr Version: docker tag :latest
Radarr Version: 5.2.6.8376
Sonarr Version: 4.0.0.748
Qbittorrent Version: 4.6.2

**Comment by Feramance** [comment]
Could you please attach your config (without API keys)? I'll take a look tomorrow morning

**Comment by Healzangels** [comment]
Sure can! Thanks for taking the time to take a peak at them. 
I've made the config a .txt file as Github didn't support attaching the .toml file type.
[config.txt](https://github.com/Feramance/qBitrr/files/13866471/config.txt)

A few changes I made:
I've mapped my host `/mnt/user/appdata/sonarr/` to container `/config/sonarr` just in case the DB paths looked a little weird since they're also mapped to the `/config` on the container Navigating to` /config/sonarr` (on the container I see my `sonarr.db` as expected.) 

I've also changed the the container mapping for my complete downloads to `/data/torrents` on the container to be more in line with other docker containers/easier for me to keep track of. But maybe introduces it's own host of problem so gladly can change that back! 

Only other thing I can think of outside of adding URLs and APIKEYs is updating Category's to be inline with what I've already been using. 

Thanks again!

**Comment by Feramance** [comment]
Alright so it is imperative that the categories in the config match those in qbittorrent, that would explain the `Downloaded scan error` with regards to the DB files, they are no longer required as of v4 update, so you can ignore those and remove extra pathing. Otherwise please update qBitrr again and let me know how you go

**Comment by Feramance** [comment]
> Also having this error, can provide config and logs as well. Otherwise im just going to keep an eye on this issue for a possible solution.
> 
> Is there a discord for support?

Not yet, not enough going on to warrant one yet

**Comment by Feramance** [comment]
Doesn't matter whether you comment the DB files config or not, it's not read anymore. Just to confirm, are you still seeing the below error?
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 2117, in db_update_single_series
    movieData = self.client.get_movie_by_movie_id(db_entry["id"])
TypeError: 'builtin_function_or_method' object is not subscriptable
'builtin_function_or_method' object is not subscriptable
```
Did you ensure that qBitrr has the appropriate permissions on the `/data/torrents` directory?

**Comment by Feramance** [comment]
Also, please provide new logs after updating to the latest version of qBitrr as I added a bit more info to the `Downloaded scan error` error

**Comment by Feramance** [comment]
Do you have Radarr, Sonarr and qBitrr all running as containers on unraid?

**Comment by Feramance** [comment]
The errors you're getting are very unusual, is it possible to have qBitrr running on a different system to test whether it's unraid related? Or better yet running your docker setup on a linux vm to test? These error aren't making sense at this point

**Comment by Healzangels** [comment]
I don't have a setup for that right now but certainly can stand a linux vm/setup over the next couple days to test! 
 
 Also I happened to notice, when I first installed QBitrr I hadn't noticed the Trackback error for Radarr. So as a quick test I changed the branch over to v3.8.12. 
 
I'm still seeing the `Pausing Completed torrent` and `Downloaded scan error:` however the Traceback error seems to have flip flopped from Radarr to Sonarr

Radarr logs are just showing the  `Pausing Completed torrent` and `Downloaded scan error:`messages and now see the below present in Sonarr.

v3.8.12.
![SonarrError](https://github.com/Feramance/qBitrr/assets/47136415/46bda81c-5218-4321-836f-d28f1c18b66a)

And swapping back to :latest see them once again under Radarr and Sonarr is just  `Pausing Completed torrent` and `Downloaded scan error:`

![RadarrError](https://github.com/Feramance/qBitrr/assets/47136415/03fd1e51-5085-43ca-aca1-f6d3143b5383)

Not sure of this is of any help but figured worth mentioning! I'll work to get a Linux VM as well to do additional testing. Thanks again!

**Comment by jsimcina** [comment]
Figured I would chime in as a datapoint as well.  I'm new to this app so I chalked these errors up to a misconfiguration of some kind:
![errors](https://github.com/Feramance/qBitrr/assets/2641033/d3671da8-23d3-4fe5-a13f-bd4196c5d4b3)

Some info about my environment, I'm running Docker under a Debian 12 VM (Proxmox).  Qbittr is sharing a stack with Qbittorrent/Gluetun but the starr apps are running in their own stack.

I switched my tag to nightly in order to get the latest and greatest with no love.

Is there any additional info I can provide?

**Comment by Healzangels** [comment]
Thanks for adding in @jsimcina looks like it'll save me a setup! Phew!

**Comment by jsimcina** [comment]
@Healzangels Happy to help haha, looks like, at least in my case, it only seems to affect Radarr, I disabled management from the config and swapped it to Sonarr only and I'm not getting any of the weirdness- so thats progress... right? :)

**Comment by Feramance** [comment]
Could you kindly update to the latest nightly build and let me know if you still get the errors?

**Comment by Healzangels** [comment]
Update branch to :nightly

Within Radarr logs only:

```
Pausing Completed torrent: [Progress: 100%][Added On: 2024-01-07 20:30:25][Availability: -100%][Time Left: 100 days, 0:00:00][Last active: 2024-01-09 10:54:08] | [TorrentState.STALLED_UPLOAD] | [Raja] That Time I Got Reincarnated as a Slime the Movie Scarlet Bond (2022) (BD Remux 1080p AVC FLAC AAC) [Dual-Audio] | Tensei shitara Slime Datta Ken Movie: Guren no Kizuna-hen (2cc05d556fb71c1c1d5fb377e8f2d044fc13d403)
Downloaded scan error: [/data/torrents/movies/That.Time.I.Got.Reincarnated.as.a.Slime.the.Movie.Scarlet.Bond.2022.1080p.BluRay.Remux.AVC.FLAC5.1.AAC2.0-Raja][2CC05D556FB71C1C1D5FB377E8F2D044FC13D403][Hardlink][Internal Server Error: The JSON value could not be converted to NzbDrone.Core.MediaFiles.MovieImport.ImportMode. Path: $.importMode | LineNumber: 0 | BytePositionInLine: 262.]
'builtin_function_or_method' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 2172, in db_update_single_series
    id = db_entry["id"]
TypeError: 'builtin_function_or_method' object is not subscriptable
'builtin_function_or_method' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 2172, in db_update_single_series
    id = db_entry["id"]
TypeError: 'builtin_function_or_method' object is not subscriptable
'builtin_function_or_method' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 2172, in db_update_single_series
    id = db_entry["id"]
TypeError: 'builtin_function_or_method' object is not subscriptable
```

Appears to be no change. Seeing the `Pausing Completed torrent` and `Downloaded scan error:` only within Sonarr.

**Comment by jsimcina** [comment]
I missed the original update due to some issues in getting portainer to pull down the newest nightly, but just as I managed to fix it, the new NEW update was pushed out (1e539d1433f7).  Same errors are coming up, but there's a change in the movieData variable:

![errors](https://github.com/Feramance/qBitrr/assets/2641033/92ca6c11-1fed-459f-93e1-cc10d5f848f8)

**Comment by Feramance** [comment]
> I missed the original update due to some issues in getting portainer to pull down the newest nightly, but just as I managed to fix it, the new NEW update was pushed out (1e539d1433f7). Same errors are coming up, but there's a change in the movieData variable:
> 
> ![errors](https://private-user-images.githubusercontent.com/2641033/295280589-92ca6c11-1fed-459f-93e1-cc10d5f848f8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MjAxODQsIm5iZiI6MTcwNDgxOTg4NCwicGF0aCI6Ii8yNjQxMDMzLzI5NTI4MDU4OS05MmNhNmMxMS0xZmVkLTQ1OWYtOTNlMS1jYzEwZDVmODQ4ZjguanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDlUMTcwNDQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDAwMTE4ZTFkODFlZWViZmJiYjUxOGUzYWYwZDQ1N2MwZjI4YTMwNTBhOTZmNWJkMWU1MWQ0MWM5OTVmYjk4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Zr8cf2sIdONMLAvvcESQXxuqB4VslvvekmhEWOFXGlk)

Yes this was my error, its fixed, try updating and checking now please

**Comment by Feramance** [comment]
I think I found the issue and I never hit it cause I don't use the search by year functionality. Please update and try again please

**Comment by jsimcina** [comment]
Well this is new :)
![errors](https://github.co1m/Feramance/qBitrr/assets/2641033/1fb1a8c9-4c86-4a71-947b-5018c007153e)

**Comment by Healzangels** [comment]
Seems promising! 

Updated and happy to say I'm not seeing the Trackback error any longer within my Radarr log! 

I am still seeing torrents pausing and the following messages with Sonarr and Radarr logs.

```
Pausing Completed torrent: [Progress: 100%][Added On: 2024-01-07 20:30:25][Availability: -100%][Time Left: 100 days, 0:00:00][Last active: 2024-01-09 10:54:08] | [TorrentState.STALLED_UPLOAD] | [Raja] That Time I Got Reincarnated as a Slime the Movie Scarlet Bond (2022) (BD Remux 1080p AVC FLAC AAC) [Dual-Audio] | Tensei shitara Slime Datta Ken Movie: Guren no Kizuna-hen (2cc05d556fb71c1c1d5fb377e8f2d044fc13d403)
Downloaded scan error: [/data/torrents/movies/That.Time.I.Got.Reincarnated.as.a.Slime.the.Movie.Scarlet.Bond.2022.1080p.BluRay.Remux.AVC.FLAC5.1.AAC2.0-Raja][2CC05D556FB71C1C1D5FB377E8F2D044FC13D403][Hardlink][Internal Server Error: The JSON value could not be converted to NzbDrone.Core.MediaFiles.MovieImport.ImportMode. Path: $.importMode | LineNumber: 0 | BytePositionInLine: 262.]
```
Thanks very much for all your time and work in solving these problems!

**Comment by Feramance** [comment]
> Well this is new :) ![errors](https://private-user-images.githubusercontent.com/2641033/295288182-a3fa87e7-222d-45f7-9249-cdd7e5f57a61.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MjE1MzAsIm5iZiI6MTcwNDgyMTIzMCwicGF0aCI6Ii8yNjQxMDMzLzI5NTI4ODE4Mi1hM2ZhODdlNy0yMjJkLTQ1ZjctOTI0OS1jZGQ3ZTVmNTdhNjEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDlUMTcyNzEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWRhMzdjM2NiNmMwMmRlOGVkMjUwMjNiYTA1ZjE0YTUzOTgyYjdjODI5ZWYyN2ZiNWIyZTAyMGNmNGM4OGM0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iYr17ZSlXCWlxrFYUcdUDX8x1-RvQ8i9btFGLQiEWZE)

Are Radarr/Sonarr and qBitrr on the same docker network? As this is a network issue, not on qBitrr's end

**Comment by Feramance** [comment]
> Seems promising!
> 
> Updated and happy to say I'm not seeing the Trackback error any longer within my Radarr log!
> 
> I am still seeing torrents pausing and the following messages with Sonarr and Radarr logs.
> 
> ```
> Pausing Completed torrent: [Progress: 100%][Added On: 2024-01-07 20:30:25][Availability: -100%][Time Left: 100 days, 0:00:00][Last active: 2024-01-09 10:54:08] | [TorrentState.STALLED_UPLOAD] | [Raja] That Time I Got Reincarnated as a Slime the Movie Scarlet Bond (2022) (BD Remux 1080p AVC FLAC AAC) [Dual-Audio] | Tensei shitara Slime Datta Ken Movie: Guren no Kizuna-hen (2cc05d556fb71c1c1d5fb377e8f2d044fc13d403)
> Downloaded scan error: [/data/torrents/movies/That.Time.I.Got.Reincarnated.as.a.Slime.the.Movie.Scarlet.Bond.2022.1080p.BluRay.Remux.AVC.FLAC5.1.AAC2.0-Raja][2CC05D556FB71C1C1D5FB377E8F2D044FC13D403][Hardlink][Internal Server Error: The JSON value could not be converted to NzbDrone.Core.MediaFiles.MovieImport.ImportMode. Path: $.importMode | LineNumber: 0 | BytePositionInLine: 262.]
> ```
> 
> Thanks very much for all your time and work in solving these problems!

Glad that's fixed, I'll push the patch, I still think there's some bad pathing or config on your end for that `Downloaded scan error` but I'll keep investigating just in case

**Comment by jsimcina** [comment]
It took about 5 minutes but it seems like the connection errors are gone.  Possibly related to dependencies within the stack that hadn't initialized?  No sign of the subscription errors and I'm seeing it identifying torrents and performing searches now!

As for my setup, I'm running two stacks, one with Gluetun, qbit, qbittr, and prowlarr- the other with the other starr apps- so who knows what kind of weird race condition I created, but it seems to have settled on its own!  Thank you for your work on this!

**Comment by Feramance** [comment]
> It took about 5 minutes but it seems like the connection errors are gone.  Possibly related to dependencies within the stack that hadn't initialized?  No sign of the subscription errors and I'm seeing it identifying torrents and performing searches now!
> 
> As for my setup, I'm running two stacks, one with Gluetun, qbit, qbittr, and prowlarr- the other with the other starr apps- so who knows what kind of weird race condition I created, but it seems to have settled on its own!  Thank you for your work on this!

Glad to hear

**Comment by Healzangels** [comment]
> > Seems promising!
> > Updated and happy to say I'm not seeing the Trackback error any longer within my Radarr log!
> > I am still seeing torrents pausing and the following messages with Sonarr and Radarr logs.
> > ```
> > Pausing Completed torrent: [Progress: 100%][Added On: 2024-01-07 20:30:25][Availability: -100%][Time Left: 100 days, 0:00:00][Last active: 2024-01-09 10:54:08] | [TorrentState.STALLED_UPLOAD] | [Raja] That Time I Got Reincarnated as a Slime the Movie Scarlet Bond (2022) (BD Remux 1080p AVC FLAC AAC) [Dual-Audio] | Tensei shitara Slime Datta Ken Movie: Guren no Kizuna-hen (2cc05d556fb71c1c1d5fb377e8f2d044fc13d403)
> > Downloaded scan error: [/data/torrents/movies/That.Time.I.Got.Reincarnated.as.a.Slime.the.Movie.Scarlet.Bond.2022.1080p.BluRay.Remux.AVC.FLAC5.1.AAC2.0-Raja][2CC05D556FB71C1C1D5FB377E8F2D044FC13D403][Hardlink][Internal Server Error: The JSON value could not be converted to NzbDrone.Core.MediaFiles.MovieImport.ImportMode. Path: $.importMode | LineNumber: 0 | BytePositionInLine: 262.]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thanks very much for all your time and work in solving these problems!
> 
> Glad that's fixed, I'll push the patch, I still think there's some bad pathing or config on your end for that `Downloaded scan error` but I'll keep investigating just in case

I'll recreate my config as well and report back if anything changes! Thanks again.

**Comment by Feramance** [comment]
Please also open a new issue copying any data you find relevant from this issue. Thanks

**Comment by Healzangels** [comment]
Awesome, will do. Going to recreate config and if issue persists will create a new issue, otherwise will update here saying all set. - Cheers!
