### ISSUE TITLE
Bad Paths Issue.

### ISSUE THREAD

**Issue by Healzangels** [Feramance/qBitrr#52]
Thanks again for the help on the Traceback issue! 

I believe I got a little further in troubleshooting my bad paths/config for the pausing of torrents I'm seeing however having difficulty pinpointing/resolving. 

I went ahead and created a new config/docker container, this time I left the default mapping of `/completed_downloads` for the container. My Unraid Docker template config looks like the following: 

![DockerConfig](https://github.com/Feramance/qBitrr/assets/47136415/5369d719-738a-4f69-ac3f-84ff36077508)

I than within the config.toml have set the following:

`CompletedDownloadFolder = "/completed_downloads"`

Checking on my QBittorrent side I have the following configured for my Default Save Path 
![Default](https://github.com/Feramance/qBitrr/assets/47136415/635a010f-9c93-4eef-ae7a-712910abc5b3)

My Qbittorent Docker is mapped Container: `/data/torrents` Host: `/mnt/user/data/torrents/`
![TorrentData](https://github.com/Feramance/qBitrr/assets/47136415/bb897735-3f71-4a26-82de-8080ac86228e)

With the settings setup as the above what I am now seeing with my log is again the Pausing of Complete torrent but also

```
Missing Torrent: [TorrentState.STALLED_UPLOAD] [LostYears] Spy x Family - S02E11 (WEB 1080p x265 10-bit AAC EAC3) [Dual-Audio] | Season 2 | S2 (dd24a3cc744058d6c6cf990090b7b15886078332) - File does not seem to exist: /data/torrents/tv/[LostYears] Spy x Family - S02E11 (WEB 1080p x265 10-bit AAC EAC3) [ACD4741A]/[LostYears] Spy x Family - S02E11 (WEB 1080p x265 10-bit AAC EAC3) [ACD4741A].mkv 
```

So something isn't mapping quiet right here. I would expect the container to see this path as `/completed_downloads/tv/[LostYears] Spy x Family - S02E11 (WEB 1080p x265 10-bit AAC EAC3) [ACD4741A]` as `/data/torrents/tv/[LostYears] Spy x Family - S02E11 (WEB 1080p x265 10-bit AAC EAC3) [ACD4741A]` is what the QBittorrent instance would see the file as? Assume that's part of my problem.

I also tried changing the path mapping on my QBitrr Docker Template to be 
Container: `/data/torrents` Host: `/mnt/user/data/torrents/`
![datatorrent](https://github.com/Feramance/qBitrr/assets/47136415/f6a7951b-64a2-49b4-b3f5-85b0c691c67b)

And updating config.toml to be 
`CompletedDownloadFolder = "/data/torrents"`

With the settings setup as above I see the pause of downloads but this time

```
Downloaded scan error: [/data/torrents/tv/[LostYears] Spy x Family - S02E11 (WEB 1080p x265 10-bit AAC EAC3) [ACD4741A]][DD24A3CC744058D6C6CF990090B7B15886078332][Hardlink][Internal Server Error: The JSON value could not be converted to NzbDrone.Core.MediaFiles.EpisodeImport.ImportMode. Path: $.importMode | LineNumber: 0 | BytePositionInLine: 227.]
```

So either I might be misunderstanding what the `CompletedDownloadFolder` should be set to or maybe I'm running into a conflict some where else. 

Typically pretty good with mapping docker/host paths so a bit stumped on where the issue is coming into play. Thanks again for all your assistance!

**Comment by Healzangels** [comment]
Hopefully that all made sense/provided OK examples of what I'm seeing. Happy to test any other combination of paths/mappings and provide screenshots and logs.

**Comment by Healzangels** [comment]
Certainly! 
Which path would you like me to test with this the /completed_downloads and the missing `Missing Torrent:`
or
`/data/torrents` which leads to `Downloaded scan error:`

Thanks

**Comment by Feramance** [comment]
With `/data/torrents` though please also set the path for the categories in qittorrent used by your Radarr/Sonarr instances to `/data/torrents` too as that could cause some issues too

**Comment by Feramance** [comment]
Set the category paths to `/data/torrents` instead of `tv` or `movies` etc. meanwhile I'll take a look at the logs

**Comment by Feramance** [comment]
Potential fix alert, please set `ImportMode = "Auto"` in the config and test again

**Comment by Feramance** [comment]
> Set the category paths to `/data/torrents` instead of `tv` or `movies` etc. meanwhile I'll take a look at the logs

This should not be necessary, but for testing sake

**Comment by Healzangels** [comment]
Awesome going to test now and will report back shortly! I'll start with just changing `ImportMode` and implement from there.

**Comment by Healzangels** [comment]
Looking promising! Updated to nightly and just changed the `ImportMode = "Auto"` only.

I am now seeing the following log output (I changed ConsoleLevel back to Debug) which seems positive? The torrents are still pausing however.

[Sonarr-TV.log](https://github.com/Feramance/qBitrr/files/13881153/Sonarr-TV.log)

TRACE level as well. 
[Sonarr-TV Trace.log](https://github.com/Feramance/qBitrr/files/13881184/Sonarr-TV.Trace.log)

Including the new Config file I've been using as well in case something there is what is causing them to pause. 
[config new.txt](https://github.com/Feramance/qBitrr/files/13881213/config.new.txt)

Thanks once again for all your updates/changes to get this working!

**Comment by Feramance** [comment]
Please keep me informed on progress so that I may push the patch if working

**Comment by Feramance** [comment]
Also, please update to the latest nightly build and let me know what torrent behaviour is like, made some changes to stop the pausing

**Comment by Feramance** [comment]
Please update to the latest nightly and test again. I have made changes to the way the pausing functionality works throughout qBitrr

**Comment by Healzangels** [comment]
Updated but unfortunately still pausing
Trace log from latest run.
[Sonarr-TV_night_updated.log](https://github.com/Feramance/qBitrr/files/13889804/Sonarr-TV_night_updated.log)

**Comment by Feramance** [comment]
Do the paused torrents still have the tag `qbitrr-allowed_Seeding` in qbittorrent?

**Comment by Healzangels** [comment]
Paused torrents not seeing the `qbitrr-allowed_Seeding` tag however have a few movies seeding as well (radarr not configured at this time) and those I am seeing the `qbitrr-allowed_Seeding` tag on. 

I can try removing a torrent and re-adding and see if the new addition gets the tag.

**Comment by Healzangels** [comment]
Removed and resent torrent down from Sonarr to Qbittorrent, downloaded fine but does pause once completed. 
Not being tagged with `qbitrr-allowed_Seeding`

**Comment by Feramance** [comment]
I'll replicate the issue as I know why I'm not experiencing it. In the mean time if you're ok with it for a day or two, set up qBitrr to work with everything as you expect it to, I will inform you once I have a solution and I also suggest downgrading the `latest` tag rather than the `nightly` tag and recreating the docker container

**Comment by Healzangels** [comment]
Super and will do, I'll have my config completely filled/ready to go for future tests.

Thanks again for all your time/assistance! I think I owe you a coffee, if you've got a link love to support all the hard work. -Cheers!

**Comment by Feramance** [comment]
By any chance, do you have any seed limits set in qbittorrent?

**Comment by Feramance** [comment]
Please test the latest nightly build, if all goes well I'll push the release

**Comment by Healzangels** [comment]
Super, updating nightly branch now and will follow up shortly!

**Comment by Healzangels** [comment]
Wahoo! Seeding is continuing and I'm seeing the `qbitrr-allowed_Seeding` applied to things in the `tv` category! 

I've attached another TRACE level log as everything looks good but maybe you'll see something I've missed.
[Sonarr-TV_1_11.log](https://github.com/Feramance/qBitrr/files/13905745/Sonarr-TV_1_11.log)

Going to do a few other quick tests but looking good! I hadn't completed the config like I mentioned yesterday (woops sorry!) but will also get that completed/tested/

Thank you very much!

**Comment by Healzangels** [comment]
Also not sure it matters anymore but just for information sake I also don't/didn't have any seeding limit set on the Qbittorrent side.

**Comment by Feramance** [comment]
Perfect, seems to be going well. Just a couple of notes, I had mentioned to change the path for the qittorrent categories but you should leave them as they are recommended by trash-guides. 

In addition, there's also a new feature available which will require you to generate a new config through qBitrr or grab the sample and copy your settings over where you'll also find a new config.

If any more issues crop up, do not hesitate to contact me again and should you have any feature requests, I'd be happy to hear

**Comment by Healzangels** [comment]
Fantastic, update config file with latest template and filled out/everything working out great! 

I had one unrelated to the issue question, but more to how to configure.

Under the Sonarr-TV section is the line `Trackers = []` which I assume is where you would specify Tracker specific setting for the tracker. Not exactly sure what the format would look like however here.

For example I don't have a separate instance of Sonarr for anime, I would like to include the Nyaa tracker in my Sonarr-TV section.
Saw for Sonarr-Anime the format appears as such but without the `Trackers = []` line.
```
[[Sonarr-Anime.Torrent.Trackers]]
Name = "Nyaa"
Priority = 10
URI = "http://nyaa.tracker.wf:7777/announce"
MaximumETA = 18000
DownloadRateLimit = -1
UploadRateLimit = -1
MaxUploadRatio = -1
MaxSeedingTime = -1
AddTrackerIfMissing = false
RemoveIfExists = false
SuperSeedMode = false
AddTags = ["qBitrr-anime"]
```
For Sonarr-TV and the `Trackers = []` would that go within the []? Apologies for misunderstanding what the configuration should look like here.

My other thought was something like

```
Trackers = []

[[Sonarr-TV.Torrent.Trackers]]
Name = "Nyaa"
Priority = 10
URI = "http://nyaa.tracker.wf:7777/announce"
MaximumETA = 18000
DownloadRateLimit = -1
UploadRateLimit = -1
MaxUploadRatio = -1
MaxSeedingTime = -1
AddTrackerIfMissing = false
RemoveIfExists = false
SuperSeedMode = false
AddTags = ["qBitrr-tv"]
```
But again wasn't sure how the `Trackers = []` comes into play here or how the proper format would look. 

Thanks once again for all your time and assistance in getting this running on my system very excited to use!

**Comment by Feramance** [comment]
I have updated the config example, I'll get around to the config generator later. The default config has 4 instances total, 2 for sonarr and 2 for radarr. However, qBitrr can handle a theoretical unlimited number of instances, just make sure you have all the config in place for the specific instance (i.e. Sonarr-TV, Sonarr-Anime, Radarr-1080, Radarr-4K, etc)

**Comment by Healzangels** [comment]
Awesome, thanks for the info/heads up on the template. 

D'oh might also have one remaining small hic-up. Might also be on my end/configuration.
[Possible Bug.log](https://github.com/Feramance/qBitrr/files/13907244/Possible.Bug.log)
Saw the following within Sonarr log, new config is back to INFO level so not sure it will have all the relevant information. 
-Cheers!

**Comment by Feramance** [comment]
That's a new issue related to a functionality upgrade to have things better in line, I'll tackle it tomorrow. Thanks for the heads up

**Comment by Feramance** [comment]
To avoid that bug and have it functional for now, set series search to false in the configs for Sonarr

**Comment by Healzangels** [comment]
Cool, just had an opportunity to copy the new template over/filled out. 
Thanks for the change/clarification on the trackers. Having a better time follow along/understand the config with the current template format! 
I've  set the seriessearch to false for the time being as well, thanks for the tip.

**Comment by Healzangels** [comment]
Also just for fun was playing around with a logo for my container on unraid. 
Made this and figured would share https://i.ibb.co/Cm0mhJ8/QBitrr-Logo.png
-Cheers!

**Comment by Feramance** [comment]
> Also just for fun was playing around with a logo for my container on unraid. 
> Made this and figured would share https://i.ibb.co/LdY6p6y/QBitrr-Logo.png
> -Cheers! 

That's actually really cool, I think I'll use it as inspiration but I'll definitely make some small changes. I'll let you know when I get to it, or you'll see it on GitHub

**Comment by Feramance** [comment]
> Awesome, thanks for the info/heads up on the template.
> 
> D'oh might also have one remaining small hic-up. Might also be on my end/configuration if t he template just updated. [Possible Bug.log](https://github.com/Feramance/qBitrr/files/13907244/Possible.Bug.log) Saw the following within Sonarr log, new config is back to INFO level so not sure it will have all the relevant information. -Cheers!

This issue should be sorted, if you encounter it again, please open another issue. Thanks
