### ISSUE TITLE
File being deleted by specific tracker

### ISSUE THREAD

**Issue by Healzangels** [Feramance/qBitrr#55]
Greetings!

Back with hopefully an easy one. Been following recent updates as well and they've been great!

I've begun noticing the files added by a specific provider is deleted almost immediately by qBitrr.
Tested with all manner of tags, allow seeding, ignore but it will always be removed.  Adding other files from a different tracker are added fine + properly tagged with allow seeding.

With qBitrr off the files dl properly. Confirmed the file has plenty of seeds so should not be an issue with stalling + can confirm with qBitrr not running. 

Setting log to trace I see the following when adding a file to qbittorrent.
![TS](https://github.com/Feramance/qBitrr/assets/47136415/d8072f22-0a26-4113-b38a-23774f21243c)

Can provide any additional logs + try additional files from the site. 

Thanks again for the awesome tool!

**Comment by Healzangels** [comment]
Thought I had solved with the FileExtensionAllowlist but am a bit unsure in this case with what I would want to add. Thanks!

**Comment by Feramance** [comment]
Adding the below to the File Extension Allow list should solve the issue:

```
"\\.r[0-9]{2}",
    ".rar",
    ".sfv"
```

**Comment by Feramance** [comment]
Did you manage?

**Comment by Feramance** [comment]
If I don't get a response soon I will be closing this issue as completed

**Comment by Healzangels** [comment]
Oh man I some how managed to turn off my notifications and not see the follow ups!
Let me test this afternoon and will close out as that seems like a glance exactly what I'll need. Thanks again!

**Comment by Feramance** [comment]
Any news?

**Comment by Healzangels** [comment]
All set! Apologies again for another delay in follow up! -Best
