### ISSUE TITLE
Sonarr/Radarr version, api changes.

### ISSUE THREAD

**Issue by MrChuw** [Feramance/qBitrr#60]
[Radarr.log](https://github.com/Feramance/qBitrr/files/14231000/Radarr.log)
[Sonarr.log](https://github.com/Feramance/qBitrr/files/14231001/Sonarr.log)

sonarr - 4.0.1.929 — Jan 20 2024    linuxserver docker
radarr - 5.2.6.8376 — Dec 24 2023  linuxserver docker

Apparently, there have been changes in the API in the latest versions, and "current_free_space" either changed its name or no longer exists.

It would be helpful to add the last known working version for both.

**Comment by Feramance** [comment]
Can you please send over your configs, this is a config issue. I run the testing branch of both Radarr and Sonarr to stay ahead and detect changes early

**Comment by Feramance** [comment]
Fixed, please update to the latest version

**Comment by Feramance** [comment]
Also just a side note, this had nothing to do with Radarr/Sonarr. I run the develop branches of both to ensure I detect any issues ahead of most people
