### ISSUE TITLE
Parametrize download loop delay

### ISSUE THREAD

**Issue by Xeboc** [Feramance/qBitrr#62]
Excellent software, thank you.  Would you accept a feature request?  Would you please parametrize this value?

https://github.com/Feramance/qBitrr/blob/master/qBitrr/arss.py#L4559

I would very much enjoy being able to slow down the request rate of these searches.  I don't need to be so quick or heavy on my indexers and shared home network.  I have a large amount of media to upgrade and spreading it out over a 1m or 5m loop would treat me well.

**Comment by Feramance** [comment]
Sure, I can have that inserted in no time. Also change the number of commands to reduce load, for example limit to just 1, helps a lot. Keep your eyes peeled for the next minor update

**Comment by Xeboc** [comment]
Thank you very much.  I have the number set to 1 as you suggest.

**Comment by Feramance** [comment]
Feature has been implemented in version 4.4.0, I'm going to leave this open for the time being in case you find any issues related to it
