### ISSUE TITLE
Doesn't ignore torrents with qBitrr-ignored tag

### ISSUE THREAD

**Issue by silentdragon14** [Feramance/qBitrr#66]
Torrents tagged with "qBitrr-ignored" are being "paused for disk space", which shouldn't be happening either since it's set to 20G but the remaining space is 4+TB.

**Comment by silentdragon14** [comment]
I've learned that the "qBitrr-ignored" tag is only considered when the category is unset.  IMO this doesn't feel intuitive.  Ignore should mean to simply ignore it, regardless of other factors.

**Comment by Feramance** [comment]
Currently the free space is the only function that's bypasses the ignore tag. I'll update that. In the meantime can you attach trace logs for the wrong free space value?

**Comment by silentdragon14** [comment]
[Sonarr-TV.log](https://github.com/Feramance/qBitrr/files/14605127/Sonarr-TV.log)

**Comment by silentdragon14** [comment]
[Uploading Sonarr-TV.log…]()

**Comment by silentdragon14** [comment]
[Sonarr-TV.log](https://github.com/Feramance/qBitrr/files/14605150/Sonarr-TV.log)

**Comment by Feramance** [comment]
This should be fixed btw, can you please confirm?

**Comment by silentdragon14** [comment]
Seems to be working now
