### ISSUE TITLE
Desired amount of free space in the downloads directory

### ISSUE THREAD

**Issue by Retr0astic** [Feramance/qBitrr#69]
Hi, I recently came across your project which met my needs for managing qbit downloads and automatically search for new torrents if existing is stalled, i also liked the fact that you can set the desired amount of free space so that hardlinks always worked and subtitles can be downloaded, but when I set it up, i had 2GB of free space set as the desired amount, even after this, the drive is always filled up until 0b of free space is available, what is the reason for this?

**Comment by Feramance** [comment]
Could you kindly attach trace logs and your config for further investigation? Also, make sure you have "pre allocate disk space" disabled in qbittorrent

**Comment by Retr0astic** [comment]
Yes, pre-allocated is disabled, sorry for the delayed response, I'm on a vacation, I have turned on trace logs, I'll upload it after it logs for a few hours.

**Comment by Retr0astic** [comment]
I've got one more issue, qbitrr deletes torrents that are errored due to not having free space.

[Radarr-4K.log](https://github.com/Feramance/qBitrr/files/14954923/Radarr-4K.log)
[Sonarr-TV.log](https://github.com/Feramance/qBitrr/files/14954924/Sonarr-TV.log)
[config.txt](https://github.com/Feramance/qBitrr/files/14954929/config.txt)

**Comment by Feramance** [comment]
The change is larger than anticipated, as I needed to overhaul the whole functionality of it, will release soon

**Comment by Retr0astic** [comment]
Thanks a lot for taking your time to fix this issue.

**Comment by Feramance** [comment]
The current nightly branch is running the beta for this overhaul

**Comment by Feramance** [comment]
Seems to be working as intended, I have push the update, let me know if you experience further issues

**Comment by Retr0astic** [comment]
> Just found a few more issues I need to tackle

I just update my image to nightly as well, I'll update you if I find any issues on my side as well.

**Comment by Retr0astic** [comment]
Just a small update on my experience on the latest build.

- Qbitrr seems to pause most torrents properly, but it doesn't pause all torrents. 

- Qbitrr deleted previously paused torrents due to free space, reason is "stale torrent".

**Comment by Feramance** [comment]
Noted, I think I know what's needed to fix this

**Comment by Feramance** [comment]
And it should only pause torrents based on priority. Meaning that if the top priority torrent once downloaded would not exceed the minimum free space, then it won't be paused. It does this check on all torrents that are in a download state only (downloading/paused). It will then only start pausing on e the minimum would be exceeded. Metadata torrents are ignored to test for staleness first

**Comment by Feramance** [comment]
Released another update, let me know how it goes

**Comment by Feramance** [comment]
I've made an additional change, switch back to the latest tag, if you notice any issues let me know, in the meantime I think I can safely consider the issue resolved, just reopen the ticket if you notice any further issues. Thank you

**Comment by Retr0astic** [comment]
The issue still persists, apart from the README, can you advice how your qBittorrent instance is setup? So I can replicate it on mine?

**Comment by Retr0astic** [comment]
The issue still persists, apart from the README, can you advice how your qBittorrent instance is setup? So I can replicate it on mine?

**Comment by Feramance** [comment]
Here are my qbittorrent configs:
![image](https://github.com/Feramance/qBitrr/assets/38938175/06780b4b-c244-41ca-9e51-ddf12c679a91)
![Screenshot 2024-05-17 100223](https://github.com/Feramance/qBitrr/assets/38938175/b0b62496-ba41-4ab4-b938-d91d0a41b76c)

**Comment by Retr0astic** [comment]
Okay, my config are pretty similar,, but it never pauses them even if there's 0B of storage. The logs show no sign of doing anything apart from showing the container is starting and checking qbitorrent version. 

[sonarr.log](https://paste.centos.org/view/261e0322)

[qbitrr.log](https://paste.centos.org/view/099a55c7)

[qbitrr config](https://paste.centos.org/view/ed50f56e)

**Comment by Feramance** [comment]
If you're on the latest version , you should have a `FreeSpace.log` in your logs folder, please make sure logs are set to trace and send it over

**Comment by Retr0astic** [comment]
Okay, here's the freespace [log](https://paste.centos.org/view/c0de9ed8)

**Comment by Feramance** [comment]
How long was this log run for please? As it's as though the process hasn't run at all yet

**Comment by Retr0astic** [comment]
The previous logs where an hour after startup.

This is [log](https://paste.centos.org/view/a7e6bb90) is almost 24 hours later. 

It seems to be working well now, looks like only the startup is slow.

**Comment by Retr0astic** [comment]
After further testing, this issue seems fixed, and the feature is working fine for me. 

I have an enhancement suggestion to this feature:

Let the script loop through all active downloads and if no downloads can satisfy the free space limit, let the highest priority download until it hits that free space limit.

**Comment by Retr0astic** [comment]
> > After further testing, this issue seems fixed, and the feature is working fine for me.
> 
> Glad to hear, might I ask what solved the problem please?
 I can't say for sure, the script didn't do anything for an hour, then started working properly, it seems to be an issue on my end.
> > I have an enhancement suggestion to this feature:
> > Let the script loop through all active downloads and if no downloads can satisfy the free space limit, let the highest priority download until it hits that free space limit.
> 
> It's a good idea though as this project has a replacement in development and this would be a minor change with a lot of code refactoring, I don't see it worth it sorry.

No need to apologize. I'm just throwing around ideas.

**Comment by Retr0astic** [comment]
I cant reproduce the slowdown. It seems to be on my end.
