### ISSUE TITLE
New User Improvements/Suggestions

### ISSUE THREAD

**Issue by LegioN7** [Feramance/qBitrr#72]
Hey! I absolutely love this and it worked amazing but I was hoping to help provide some new user experience frustrations.

### **Initial Setup**
**Config Overwrite issue**
If you edit the config but forget to rename it, and run the exe. It will overwrite everything.
I'd suggest preventing the edit of the config once it's created. I had that happen a few times.

**Sonarr/Radarr Configuration**
For single configurations like mine. I use 1 Sonarr for Anime, TV, and Cartoons (both 1080p and 4k), and Radarr (1080p/4k) because I have the storage capacity. The .exe throws an error when I have used the same configuration (I.E. TV shows and Anime)

**Connection Validation**
Can you validate the connection to Sonarr/Radarr/Overseerr on launch? This might help with the logging piece.

### **Readme / Wiki Suggestions**
For new folks, it might help explaining the storage location has to be /
You don't throw an error for mismatched storage, and the .exe just closes.

Explaining what format you need the "Arrs" IP location in would be great (I couldn't get localhost to work period)
As for port/IP configuration, it's odd that qbittorrent is port is separated but Sonarr/Radarr/Overseerr are not.
It would be helpful to be consistent.

**Error Logging**
Some verbose error logging would be great instead of crashing. 
Storage Location Error
"Arrs" Connection Validation

This is amazing, and I really appreciate it. If I had more expertise with Python scripting I would contribute!

**Comment by Feramance** [comment]
Hi, happy to see you're liking this project. To answer your questions/suggestions:

### **Initial Setup**
**Config Overwrite issue**
This would be a small change and might get to it after fixing the minimum free space issue which is taking longer than expected (for good reasons).

**Sonarr/Radarr Configuration**
For single configurations like yours, you can just delete the extra instances in the sample config. qBitrr supports virtually infinite instances of those by simply adding more configs, or removing any you don't use.

**Connection Validation**
Connection validation is done, if you're not seeing this in the logs then increase your logging level.


### **Readme / Wiki Suggestions**
Storage location for what exactly? You can customise paths to your hearts content so I'm not sure what you mean.

Regarding the IPs, yes this is true, unfortunately I won't be changing it as it could potentially kill existing installs. When the new version comes out it won't be an issue anymore and hopefully I'll have time to finish it sooner than later.

**Error Logging**
You can get verbose logging by changing the logging level to `TRACE`

Happy to answer or help in anyway I can

**Comment by LegioN7** [comment]
For the wiki, some basic instruction changes such as the torrent download location is what I meant. I hope this makes sense :) 
(This is primarily instruction updates for new users)

**Example**
Instead of the default copy and paste from qBittorrent - it has to be in this fashion
"D:/Torrents/Downloads"
instead of the default from Qbit
"D:\Torrents\Downloads"

As for the logging, what I meant was providing errors for the user to decipher what is causing issues.
Example:
Although I don't mind turning on verbose, when your base initial launch of the program fails, it just crashes with info.
i.e. if the storage location is invalid (as above), qbittr just crashes. There was no logging I could grab, and it was failing to start so no logging was being created.

Hope this helps! :)

**Comment by Feramance** [comment]
I added the path details to the config file and added more log file generation
