### ISSUE TITLE
Adding new ArrErrorCodesToBlocklist doesn't work? or am I doing something wrong?

### ISSUE THREAD

**Issue by IkkixD** [Feramance/qBitrr#79]
I tried to add more to blocklist, but it doesn't look like it's doing anything with them in queue, they just sit there failed as usual

ArrErrorCodesToBlocklist = ["Unable to determine if file is a sample", "Not an upgrade for existing movie file(s)", "Not a preferred word upgrade for existing movie file(s)", "Episode file on disk contains more episodes than this file contains", "was not found in the grabbed release: ", "Episode file already imported at", "Found matching series via grab history, but release was matched to series by ID. Automatic import is not possible. See the FAQ for details."]

**Comment by Feramance** [comment]
As in your other ticket, please set logs to trace and provide them, following that I'll investigate further

**Comment by Feramance** [comment]
Issue will be closed if there is no reply

**Comment by Feramance** [comment]
I'll investigate this but closing the issue
