### ISSUE TITLE
Permission Error - Operation not permitted

### ISSUE THREAD

**Issue by devanteweary** [Feramance/qBitrr#82]
Hello!

Trying to get this to run on my Unraid system.
While the container starts, it doesn't do anything and I see this in the log:

- PermissionError: [Errno 1] Operation not permitted: '/config/qBitManager'

I can't find a way to get a log since when I click on qBitrr > Logs, a console window pops up then immediately goes away.
However, I have container logs going to a syslog server. (find below)

I even had the container create a /config/qBitManager folder in case it was because it couldn't find that folder.

Thank you for any advice!!!

Container settings:
![image](https://github.com/Feramance/qBitrr/assets/29805497/e38d4e4c-a3ff-45f8-a4ec-5e49d8742279)

Logs:
![image](https://github.com/Feramance/qBitrr/assets/29805497/cf1dfcf1-6258-4d92-87b1-3cac85d2e036)

**Comment by Feramance** [comment]
This to me looks like a folder permissions issue. I suggest you recheck your variables too as you're passing the dB files which are no longer used, and create a single config folder to be linked and ensure the container has the appropriate permissions.

**Comment by devanteweary** [comment]
> This to me looks like a folder permissions issue. I suggest you recheck your variables too as you're passing the dB files which are no longer used and the restart timer was removed too, and create a single config folder to be linked and ensure the container has the appropriate permissions.

OK the config also mentioned those DB files so I just completely removed everything and started fresh.
On Unraid, I also had to go in and chmod 777 on the /appdata/qbitrr directory.

After that I noticed the config it created had some differences so just started over with that and now it's all working. Thank you!

**Comment by Feramance** [comment]
Glad to hear it's working, yes there have been a number of changes since version 2.x.x
