### ISSUE TITLE
native Apple Silicon support (docker)

### ISSUE THREAD

**Issue by kstlouis** [Feramance/qBitrr#90]
Building using Docker Compose on an M1 Mac mini. Getting an error when pulling the image:

"no matching manifest for linux/arm64/v8 in the manifest list entries"

I was able to work around this by specifying `platform: linux/amd64` in the compose file (I think; haven't fully tested everything out yet!), but just wanted to give a heads up in case this could a) be properly fixed or b) just called out in the usage/setup steps somewhere 👍

**Comment by Feramance** [comment]
I'll look into building a docker image using linux/arm64 and let you know how it goes

**Comment by kstlouis** [comment]
@Feramance yep that looks like it worked!

**Comment by kstlouis** [comment]
Again, I haven't fully tested either build in terms of features, etc on my machine yet, but this one at least can be pulled/spun up without any issues.

**Comment by Feramance** [comment]
Excellent, realistically its a python script so it should have no issues on arm, if you meet any other problems let me know, I'll be closing this particular ticket in the meantime
