### ISSUE TITLE
Overseerr link needs update

### ISSUE THREAD

**Issue by Velox-Aequitas** [Feramance/qBitrr#97]
https://github.com/Feramance/qBitrr/blob/25cba250e35eae4b616003f96df40b2ef6c34674/qBitrr/arss.py#L615

I noticed errors on my overseer connection.  The URI is appended with /api/v1/request, it looks as thought this has been upgraded to v2

![image](https://github.com/user-attachments/assets/c3ac45f6-ea55-4884-b352-2b7ff941914d)

**Comment by Feramance** [comment]
Hi, what version of Overseerr are you using as the endpoint seems to be `/api/v1` for me still?

**Comment by Velox-Aequitas** [comment]
Hello,

I'm running 1.33.2.

**Comment by Feramance** [comment]
What is the response you get if you enter the URL manually on your browser?

**Comment by Feramance** [comment]
Can you try running `{self.overseerr_uri}/api/v1/request` in your browser? Substituting `{self.overseerr_uri}` with your overseerr url (ip:port)

**Comment by Velox-Aequitas** [comment]
It was a port issue.  Completely my fault.  Sorry for wasting your time.

**Comment by Feramance** [comment]
No worries, glad to hear all is well
